universe = vanilla
executable = /data/user/tvaneede/muon_tagging/h5_production/run_h5.sh
notification = Never
IWD = $ENV(HOME)
request_memory = 2.0 GB
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_output_files = ""
+FileSystemDomain = "notarealdomain"
arguments = -o $(OUTFILE) $(INFILE)
output = $(LOGDIR)/$(JOBID).out
error  = $(LOGDIR)/$(JOBID).err
log    = $(LOGDIR)/$(JOBID).log
requirements = (TARGET.has_ssse3) && (TARGET.has_avx2)
queue 1
